version: "3.8"  # Specifies the version of Docker Compose

services:

  mongo:
    image: mongo  # Uses the official MongoDB image from Docker Hub
    volumes:
      - mongodb:/data/db  # Persists MongoDB data between container restarts
    ports:
      - 27017:27017  # Maps port 27017 on the host to port 27017 on the container

  mongo-express:
    image: mongo-express  # Uses the Mongo Express image to provide a web-based MongoDB admin interface
    ports:
      - 8081:8081  # Maps port 8081 on the host to port 8081 on the container

  flask-app:
    build:
      context: .
      dockerfile: ic_docker  # Build the image from the Dockerfile in the current directory
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}  # Pass your Google API key as an environment variable
    ports:
      - 6000:6000  # Maps port 6000 on the host to port 6000 on the container
    depends_on:
      - mongo  # Ensure mongo service starts before the flask app

  main-app:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - 80:8000
    # ports:
    # - 8000:8000 #if local
    depends_on:
      - mongo  # Ensure mongo service starts before the main app
      - flask-app  # Ensure flask app is started before the main app

volumes:
  mongodb:  # Defines a named volume to persist MongoDB data

