# Use an official Python runtime as a parent image
FROM pytorch/pytorch

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . ./ 
# Install the necessary packages
RUN pip install --timeout=100 --no-cache-dir Flask Flask-Login Flask-SocketIO python-dotenv pymongo google-generativeai Pillow sentence-transformers cohere

# Make ports available
EXPOSE 8000
# Run the application
CMD ["python", "main.py"]  
